name: synthetic-financial-data-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0
  - pip:
    - gradio==4.44.0
    - pandas==2.1.4
    - numpy==1.26.2
    - python-dotenv==1.0.0
    - google-generativeai==0.3.2
    - faker==20.1.0
    - python-dateutil==2.8.2
    - google-api-python-client==2.108.0
    - googlesearch-python==1.2.3
    - openpyxl==3.1.2
    - lxml==4.9.3
    - pyarrow==14.0.1
    - pytest==7.4.3
    - pytest-cov==4.1.0
    - pytest-asyncio==0.21.1
    - loguru==0.7.2
    - black==23.12.1
    - flake8==6.1.0
    - mypy==1.7.1
    - tqdm==4.66.1
    - requests==2.31.0
    - pydantic==2.5.2
    - pydantic-settings==2.1.0